name: game_settings
primary_key: '!singleton'
columns:
- name: league_join_private_max
  data_type: INTEGER
  tests:
  - not_null
- name: league_join_public_max
  data_type: INTEGER
  tests:
  - not_null
- name: league_max_size_public_classic
  data_type: INTEGER
  tests:
  - not_null
- name: league_max_size_public_h2h
  data_type: INTEGER
  tests:
  - not_null
- name: league_max_size_private_h2h
  data_type: INTEGER
  tests:
  - not_null
- name: league_max_ko_rounds_private_h2h
  data_type: INTEGER
  tests:
  - not_null
- name: league_prefix_public
  data_type: TEXT
  tests:
  - not_null
- name: league_points_h2h_win
  data_type: INTEGER
  tests:
  - not_null
- name: league_points_h2h_lose
  data_type: INTEGER
  tests:
  - not_null
- name: league_points_h2h_draw
  data_type: INTEGER
  tests:
  - not_null
- name: league_ko_first_instead_of_random
  data_type: BOOLEAN
  tests:
  - not_null
- name: cup_start_event_id
  data_type: TEXT
- name: cup_stop_event_id
  data_type: TEXT
- name: cup_qualifying_method
  data_type: TEXT
- name: cup_type
  data_type: TEXT
- name: featured_entries
  data_type: JSON
  tests:
  - not_null
- name: element_sell_at_purchase_price
  data_type: BOOLEAN
  tests:
  - not_null
- name: percentile_ranks
  data_type: JSON
  tests:
  - not_null
- name: underdog_differential
  data_type: INTEGER
  tests:
  - not_null
- name: squad_squadplay
  data_type: INTEGER
  tests:
  - not_null
- name: squad_squadsize
  data_type: INTEGER
  tests:
  - not_null
- name: squad_special_min
  data_type: TEXT
- name: squad_special_max
  data_type: TEXT
- name: squad_team_limit
  data_type: INTEGER
  tests:
  - not_null
- name: squad_total_spend
  data_type: INTEGER
  tests:
  - not_null
- name: ui_currency_multiplier
  data_type: INTEGER
  tests:
  - not_null
- name: ui_use_special_shirts
  data_type: BOOLEAN
  tests:
  - not_null
- name: ui_special_shirt_exclusions
  data_type: JSON
  tests:
  - not_null
- name: stats_form_days
  data_type: INTEGER
  tests:
  - not_null
- name: sys_vice_captain_enabled
  data_type: BOOLEAN
  tests:
  - not_null
- name: transfers_cap
  data_type: INTEGER
  tests:
  - not_null
- name: transfers_sell_on_fee
  data_type: DOUBLE
  tests:
  - not_null
- name: max_extra_free_transfers
  data_type: INTEGER
  tests:
  - not_null
- name: league_h2h_tiebreak_stats
  data_type: JSON
  tests:
  - not_null
- name: timezone
  data_type: TEXT
  tests:
  - not_null
